Platform.mods.kubejs.name = 'Eternity',
Platform.mods.avaritia.name = 'Avaritia [+ Eternity]',
Platform.mods.extradisks.name = 'Extra Disks (Refined Storage)',
Platform.mods.rsinsertexportupgrade.name = 'RS Insert Export Upgrade (Refined Storage)',
Platform.mods.rsinfinitybooster.name = 'RSInfinityBooster (Refined Storage)',
Platform.mods.arseng.name = 'Ars Energistique (Applied Energistics 2)',
Platform.mods.ae2things.name = 'AE2 Things (Applied Energistics 2)',
Platform.mods.megacells.name = 'MEGA Cells (Applied Energistics 2)',
Platform.mods.ae2wtlib.name = 'AE2WTLib (Applied Energistics 2)',
Platform.mods.ae2insertexportcard.name = 'AE2 Insert Export Card (Applied Energistics 2)',
Platform.mods.aeinfinitybooster.name = 'AEInfinityBooster (Applied Energistics 2)',

StartupEvents.registry('item', event => {
  event.create('estelar_obsidium_ingot').displayName('Estelar Obsidium Ingot'),
  event.create('estelar_obsidium_nugget').displayName('Estelar Obsidium Nugget'),
  event.create('mechanical_part').displayName('Mechanical Part'),
  event.create('soul_catalyst').displayName('Soul Catalyst'),
  event.create('purple_soul').displayName('Purple Soul'),
  event.create('red_soul').displayName('Red Soul'),
  event.create('blue_soul').displayName('Blue Soul'),
  event.create('green_soul').displayName('Green Soul'),
  event.create('awakened_draconium_plate').displayName('Awakened Draconium Plate'),
  event.create('crystal_matrix_plate').displayName('Crystal Matrix Plate'),
  event.create('dark_matter_plate').displayName('Dark Matter Plate'),
  event.create('draconium_plate').displayName('Draconium Plate'),
  event.create('neutronium_plate').displayName('Neutronium Plate'),
  event.create('red_matter_plate').displayName('Red Matter Plate'),
  event.create('infinity_plate').displayName('Infinity Plate'),
  event.create('eternity_core').displayName('Eternity Core'),
  event.create('eternity_ingot').displayName('Eternity Ingot'),
  event.create('eternity_shaper').displayName('Eternity Shaper')
})
