
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = false
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = false
	hide_sidebar = true
	hide_bossbar = true
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "minecraft"
	name_color = 8900331
	value_color = 16777215
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "coords"
	name_color = 16766720
	color_x = 16729344
	color_y = 4390722
	color_z = 2003199
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = false
		chunk_coords = false

[[modules_left]]
	name = "server"
	name_color = 11119017
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = false
		packets_received = false

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "location"
	name_color = 9662683
	value_color = 16777215
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = true
		light = true
		light_server = false
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = false
		day_ticks = false
		days_played = true
		slime_chunk = false

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "entity"
	name_color = 16753920
	value_color = 16777215
	total_entities_color = 16776960
	enabled = true

	[modules_left.lines]
		particles = true
		entities = true
		monster = true
		creature = true
		ambient = true
		axolotls = false
		underground_water_creature = false
		water_creature = false
		water_ambient = false
		misc = false
		glares = false
		rascals = false
		aether_surface_monster = false
		aether_darkness_monster = false
		aether_sky_monster = false
		aether_aerwhale = false

[[modules_right]]
	name = "system"
	name_color = 64154
	value_color = 16777215
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = false
		java_version = false
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		gpu_utilization = true
		opengl_version = false
		gpu_driver = false

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 9109504
	value_color = 16777215
	enabled = true

	[modules_right.lines]
		targeted_block = true
		id_block = true
		block_states = true
		block_tags = false
		nothing = true
		targeted_fluid = true
		id_fluid = true
		fluid_states = true
		fluid_tags = true
		nothing2 = true
		targeted_entity = true

